import { GeneratedFile, Language, WizardState } from "../types";
import { RECOMMENDED_NODE_VERSION } from "../constants";

const protectedFiles = new Set([
  "README.md",
  "LICENSE",
  "SECURITY.md",
  "CHANGELOG.md",
  ".editorconfig",
  ".prettierrc.json",
  ".github/dependabot.yml",
  ".github/dependabot.yaml",
  ".github/workflows/ci.yml",
  ".github/workflows/ci.yaml",
  ".github/workflows/release.yml",
  ".github/workflows/release.yaml",
  ".github/ISSUE_TEMPLATE/bug_report.md",
  ".github/ISSUE_TEMPLATE/feature_request.md",
  ".github/PULL_REQUEST_TEMPLATE.md",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
  "mkdocs.yml",
  "docs/README.md",
  "docs/index.md",
  "docs/guide.md",
  "docs/architecture.md",
  ".github/workflows/codeql.yml",
  ".github/workflows/codeql.yaml",
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
  "bun.lockb",
  ".nvmrc",
  "go.sum",
  "Cargo.lock",
  "Dockerfile",
  ".dockerignore",
  ".husky/pre-commit",
  ".husky/.gitignore",
]);

const toFile = (path: string, content: string, language?: string): GeneratedFile => ({
  path,
  content,
  language,
});

const normalizeName = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, "-")
    .replace(/^-+|-+$/g, "") || "my-repo";

const normalizeNodeVersion = (value?: string | null) => {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  const match = trimmed.match(/\d+(?:\.\d+){0,2}/);
  return match ? match[0] : null;
};

const resolveNodeVersion = (state: WizardState) =>
  normalizeNodeVersion(state.techStack.nodeVersion) || RECOMMENDED_NODE_VERSION;

const buildReadme = (state: WizardState) => {
  const title = state.projectDetails.name || "New Repository";
  const description =
    state.projectDetails.description || "A bootstrapped repository generated by GitUp.";
  return `# ${title}\n\n${description}\n`;
};

const buildLicense = (license: string) => `TODO: Add the ${license} license text here.\n`;

const buildSecurity = () => `# Security Policy\n\nPlease report security issues privately.\n`;

const buildChangelog = () => `# Changelog\n\n## [Unreleased]\n- Initial scaffold\n`;

const buildEditorConfig = () =>
  `root = true\n\n[*]\ncharset = utf-8\nindent_style = space\nindent_size = 2\nend_of_line = lf\ninsert_final_newline = true\ntrim_trailing_whitespace = true\n`;

const buildPrettierConfig = () =>
  JSON.stringify(
    {
      printWidth: 100,
      singleQuote: false,
      trailingComma: "all",
    },
    null,
    2,
  ) + "\n";

const buildIssueTemplate = (title: string) =>
  `# ${title}\n\n## Summary\n\n## Steps to Reproduce\n\n## Expected Behavior\n\n## Actual Behavior\n`;

const buildPullRequestTemplate = () =>
  `## Summary\n\n## Testing\n\n## Checklist\n- [ ] Tests added/updated\n- [ ] Docs updated\n`;

const buildContributing = () =>
  `# Contributing\n\nThanks for contributing! Please open an issue before major changes.\n`;

const buildCodeOfConduct = () => `# Code of Conduct\n\nBe respectful and inclusive.\n`;

const buildDependabot = (ecosystem: string) =>
  `version: 2\nupdates:\n  - package-ecosystem: "${ecosystem}"\n    directory: "/"\n    schedule:\n      interval: "weekly"\n`;

const buildRuffConfig = () => `line-length = 100\nselect = ["E", "F", "I"]\n`;

const buildNvmrc = (nodeVersion: string) => `${nodeVersion}\n`;

const buildDockerignore = () =>
  [
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".git",
    ".github",
    ".vscode",
    ".DS_Store",
    "__pycache__",
    "*.pyc",
    "target",
  ].join("\n") + "\n";

const buildDockerfile = (state: WizardState, nodeVersion: string) => {
  switch (state.techStack.language) {
    case Language.PYTHON:
      return `FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nRUN python -m pip install --upgrade pip\nRUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi\nCMD ["python", "main.py"]\n`;
    case Language.GO:
      return `FROM golang:1.22-alpine AS builder\nWORKDIR /app\nCOPY . .\nRUN go build -o app .\n\nFROM alpine:3.19\nWORKDIR /app\nCOPY --from=builder /app/app ./app\nCMD ["./app"]\n`;
    case Language.RUST: {
      const binaryName = normalizeName(state.projectDetails.name);
      return `FROM rust:1 AS builder\nWORKDIR /app\nCOPY . .\nRUN cargo build --release\n\nFROM debian:bookworm-slim\nWORKDIR /app\nCOPY --from=builder /app/target/release/${binaryName} ./app\nCMD ["./app"]\n`;
    }
    default: {
      const pm = state.techStack.packageManager || "npm";
      const usesCorepack = pm === "pnpm" || pm === "yarn";
      const installCmd =
        pm === "pnpm"
          ? "pnpm install --frozen-lockfile"
          : pm === "yarn"
            ? "yarn install --frozen-lockfile"
            : pm === "bun"
              ? "bun install"
              : "npm install";
      const entrypoint =
        state.techStack.language === Language.JAVASCRIPT ? "src/index.js" : "src/index.ts";
      const bunSetup = pm === "bun" ? "RUN npm install -g bun\n" : "";
      const corepack = usesCorepack ? "RUN corepack enable\n" : "";
      return `FROM node:${nodeVersion}-alpine\nWORKDIR /app\nCOPY . .\n${corepack}${bunSetup}RUN ${installCmd}\nCMD ["node", "${entrypoint}"]\n`;
    }
  }
};

const buildHuskyPreCommit = (state: WizardState) => {
  const lines = ["#!/bin/sh", "set -e"];
  const commands: string[] = [];
  const pm = state.techStack.packageManager || "npm";

  if (state.techStack.language === Language.PYTHON) {
    if (state.automation.linting) commands.push("python -m ruff check .");
    if (state.automation.tests) commands.push("python -m pytest");
  } else if (state.techStack.language === Language.GO) {
    if (state.automation.linting) commands.push("go vet ./...");
    if (state.automation.tests) commands.push("go test ./...");
  } else if (state.techStack.language === Language.RUST) {
    if (state.automation.linting) commands.push("cargo clippy -- -D warnings");
    if (state.automation.tests) commands.push("cargo test");
  } else {
    if (state.automation.linting) commands.push(`${pm} run lint`);
    if (state.automation.tests) commands.push(`${pm} run test`);
  }

  if (commands.length === 0) {
    commands.push('echo "No pre-commit checks configured"');
  }

  return `${lines.concat(commands).join("\n")}\n`;
};

const buildCiWorkflow = (nodeVersion: string, installCmd: string, runCmd: string[]) => {
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-node@v4",
    `        with:\n          node-version: "${nodeVersion}"`,
    `      - run: ${installCmd}`,
    ...runCmd.map((cmd) => `      - run: ${cmd}`),
  ];

  return `name: CI\non:\n  push:\n  pull_request:\n${buildWorkflowConcurrency("ci")}jobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n${steps.join("\n")}\n`;
};

const buildReleaseWorkflow = (language: Language, nodeVersion: string) => {
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-node@v4",
    `        with:\n          node-version: "${nodeVersion}"`,
    "      - run: npm install",
    "      - run: npm run build",
    "      - run: npm pack",
  ];

  if (language === Language.PYTHON) {
    steps.push("      - uses: actions/setup-python@v5");
    steps.push('        with:\n          python-version: "3.12"');
    steps.push("      - run: python -m pip install --upgrade pip");
    steps.push("      - run: python -m pip install build");
    steps.push("      - run: python -m build");
  }

  if (language === Language.GO) {
    steps.push("      - uses: actions/setup-go@v5");
    steps.push('        with:\n          go-version: "1.22"');
    steps.push("      - run: go build ./...");
  }

  if (language === Language.RUST) {
    steps.push("      - uses: dtolnay/rust-toolchain@stable");
    steps.push("        with:\n          components: clippy,rustfmt");
    steps.push("      - run: cargo build --release");
  }

  steps.push("      - uses: softprops/action-gh-release@v2");
  steps.push("        with:\n          generate_release_notes: true");

  return `name: Release\non:\n  push:\n    tags:\n      - "v*.*.*"\n  workflow_dispatch:\n${buildWorkflowConcurrency("release")}jobs:\n  release:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: write\n    steps:\n${steps.join("\n")}\n`;
};

const buildCodeqlWorkflow = (language: Language) => {
  const codeqlLang =
    language === Language.PYTHON
      ? "python"
      : language === Language.GO
        ? "go"
        : "javascript-typescript";

  return `name: CodeQL\non:\n  push:\n  pull_request:\nschedule:\n  - cron: "0 3 * * 1"\n${buildWorkflowConcurrency("codeql")}jobs:\n  analyze:\n    runs-on: ubuntu-latest\n    permissions:\n      actions: read\n      contents: read\n      security-events: write\n    steps:\n      - uses: actions/checkout@v4\n      - uses: github/codeql-action/init@v3\n        with:\n          languages: ${codeqlLang}\n      - uses: github/codeql-action/analyze@v3\n`;
};

const buildWorkflowConcurrency = (name: string) =>
  `concurrency:\n  group: "${name}-\${{ github.ref }}"\n  cancel-in-progress: true\n`;

const buildPythonCiWorkflow = (commands: string[]) => {
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-python@v5",
    '        with:\n          python-version: "3.12"',
    "      - run: python -m pip install --upgrade pip",
    "      - run: python -m pip install -r requirements.txt",
    ...commands.map((cmd) => `      - run: ${cmd}`),
  ];

  return `name: CI\non:\n  push:\n  pull_request:\n${buildWorkflowConcurrency("ci")}jobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n${steps.join("\n")}\n`;
};

const buildGoCiWorkflow = (commands: string[]) => {
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-go@v5",
    '        with:\n          go-version: "1.22"',
    ...commands.map((cmd) => `      - run: ${cmd}`),
  ];

  return `name: CI\non:\n  push:\n  pull_request:\n${buildWorkflowConcurrency("ci")}jobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n${steps.join("\n")}\n`;
};

const buildRustCiWorkflow = (commands: string[]) => {
  const steps = [
    "      - uses: actions/checkout@v4",
    "      - uses: dtolnay/rust-toolchain@stable",
    "        with:\n          components: clippy,rustfmt",
    ...commands.map((cmd) => `      - run: ${cmd}`),
  ];

  return `name: CI\non:\n  push:\n  pull_request:\n${buildWorkflowConcurrency("ci")}jobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n${steps.join("\n")}\n`;
};

const buildPackageJson = (state: WizardState, nodeVersion: string) => {
  const name = normalizeName(state.projectDetails.name);
  const scripts: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};

  if (state.automation.linting) scripts.lint = "eslint .";
  if (state.automation.tests) scripts.test = "vitest run";
  if (state.automation.formatting) {
    scripts.format = "prettier . --write";
    scripts["format:check"] = "prettier . --check";
  }
  if (state.automation.husky) {
    scripts.prepare = "husky install";
    devDependencies.husky = "^9.0.0";
  }
  scripts.build = 'echo "Add build step"';

  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: state.projectDetails.visibility !== "public",
      scripts,
      engines: { node: nodeVersion },
      packageManager: state.techStack.packageManager || undefined,
      devDependencies: Object.keys(devDependencies).length > 0 ? devDependencies : undefined,
    },
    null,
    2,
  ).replace(/\n}\n$/, "\n}\n");
};

const buildJsLockfile = (packageManager: string) => {
  switch (packageManager) {
    case "pnpm":
      return { path: "pnpm-lock.yaml", content: "lockfileVersion: 9\n" };
    case "yarn":
      return { path: "yarn.lock", content: "# yarn lockfile v1\n" };
    case "bun":
      return { path: "bun.lockb", content: "" };
    case "npm":
    default:
      return {
        path: "package-lock.json",
        content: JSON.stringify({ name: "app", lockfileVersion: 3 }, null, 2) + "\n",
      };
  }
};

const buildPythonProject = (state: WizardState) => {
  const name = normalizeName(state.projectDetails.name);
  return `# Generated by GitUp\n[project]\nname = "${name}"\nversion = "0.1.0"\nrequires-python = ">=3.11"\n`;
};

const buildGoMod = (state: WizardState) => {
  const name = normalizeName(state.projectDetails.name);
  return `module ${name}\n\ngo 1.22\n`;
};

const buildCargoToml = (state: WizardState) => {
  const name = normalizeName(state.projectDetails.name);
  return `# Generated by GitUp\n[package]\nname = "${name}"\nversion = "0.1.0"\nedition = "2021"\n`;
};

const buildPythonRequirements = (state: WizardState) => {
  const requirements: string[] = [];
  if (state.automation.tests) requirements.push("pytest");
  if (state.automation.linting || state.automation.formatting) requirements.push("ruff");
  return requirements.join("\n") + "\n";
};

const buildEntryPoints = (state: WizardState) => {
  switch (state.techStack.language) {
    case Language.PYTHON:
      return [toFile("main.py", 'print("Hello from GitUp")\n', "python")];
    case Language.GO:
      return [
        toFile(
          "main.go",
          'package main\n\nimport "fmt"\n\nfunc main() {\n  fmt.Println("Hello from GitUp")\n}\n',
          "go",
        ),
      ];
    case Language.RUST:
      return [toFile("src/main.rs", 'fn main() {\n    println!("Hello from GitUp");\n}\n', "rust")];
    case Language.JAVASCRIPT:
      return [toFile("src/index.js", 'console.log("Hello from GitUp");\n', "javascript")];
    default:
      return [toFile("src/index.ts", 'console.log("Hello from GitUp");\n', "typescript")];
  }
};

const buildTestFiles = (state: WizardState) => {
  switch (state.techStack.language) {
    case Language.PYTHON:
      return [toFile("tests/test_basic.py", "def test_basic():\n    assert True\n")];
    case Language.GO:
      return [
        toFile(
          "main_test.go",
          'package main\n\nimport "testing"\n\nfunc TestBasic(t *testing.T) {}\n',
          "go",
        ),
      ];
    case Language.RUST:
      return [toFile("tests/basic.rs", "#[test]\nfn basic() {\n    assert!(true);\n}\n", "rust")];
    default:
      return [
        toFile(
          "tests/basic.test.ts",
          'import { describe, it, expect } from "vitest";\n\ndescribe("basic", () => {\n  it("works", () => {\n    expect(true).toBe(true);\n  });\n});\n',
          "typescript",
        ),
      ];
  }
};

export const buildBaselineScaffold = (state: WizardState): GeneratedFile[] => {
  const files: GeneratedFile[] = [];
  const nodeVersion = resolveNodeVersion(state);

  files.push(toFile("README.md", buildReadme(state)));

  if (state.projectDetails.license.toLowerCase() !== "none") {
    files.push(toFile("LICENSE", buildLicense(state.projectDetails.license)));
  }

  if (state.automation.securityDocs) {
    files.push(toFile("SECURITY.md", buildSecurity()));
  }

  if (state.automation.release) {
    files.push(toFile("CHANGELOG.md", buildChangelog()));
  }

  if (state.automation.formatting) {
    files.push(toFile(".editorconfig", buildEditorConfig()));
    if (
      state.techStack.language === Language.TYPESCRIPT ||
      state.techStack.language === Language.JAVASCRIPT
    ) {
      files.push(toFile(".prettierrc.json", buildPrettierConfig()));
    }
  }

  if (state.governance.contributionGuide) {
    files.push(toFile("CONTRIBUTING.md", buildContributing()));
  }

  if (state.governance.codeOfConduct !== "none") {
    files.push(toFile("CODE_OF_CONDUCT.md", buildCodeOfConduct()));
  }

  if (state.governance.issueTemplates) {
    files.push(toFile(".github/ISSUE_TEMPLATE/bug_report.md", buildIssueTemplate("Bug Report")));
    files.push(
      toFile(".github/ISSUE_TEMPLATE/feature_request.md", buildIssueTemplate("Feature Request")),
    );
  }

  if (state.governance.pullRequestTemplate) {
    files.push(toFile(".github/PULL_REQUEST_TEMPLATE.md", buildPullRequestTemplate()));
  }

  if (state.automation.dependabot) {
    const ecosystem =
      state.techStack.language === Language.PYTHON
        ? "pip"
        : state.techStack.language === Language.GO
          ? "gomod"
          : state.techStack.language === Language.RUST
            ? "cargo"
            : "npm";
    files.push(toFile(".github/dependabot.yml", buildDependabot(ecosystem)));
  }

  if (state.automation.ci) {
    if (
      state.techStack.language === Language.TYPESCRIPT ||
      state.techStack.language === Language.JAVASCRIPT
    ) {
      const pm = state.techStack.packageManager || "npm";
      const installCmd =
        pm === "pnpm"
          ? "pnpm install"
          : pm === "yarn"
            ? "yarn"
            : pm === "bun"
              ? "bun install"
              : "npm install";
      const runCmd: string[] = [];
      if (state.automation.linting) runCmd.push(`${pm} run lint`);
      if (state.automation.tests) runCmd.push(`${pm} run test`);
      if (state.automation.formatting) runCmd.push(`${pm} run format:check`);
      runCmd.push(`${pm} run build`);
      files.push(
        toFile(".github/workflows/ci.yml", buildCiWorkflow(nodeVersion, installCmd, runCmd)),
      );
    } else if (state.techStack.language === Language.PYTHON) {
      const runCmd: string[] = [];
      if (state.automation.linting) runCmd.push("python -m ruff check .");
      if (state.automation.formatting) runCmd.push("python -m ruff format --check .");
      if (state.automation.tests) runCmd.push("python -m pytest");
      files.push(toFile(".github/workflows/ci.yml", buildPythonCiWorkflow(runCmd)));
    } else if (state.techStack.language === Language.GO) {
      const runCmd: string[] = [];
      if (state.automation.formatting) runCmd.push('test -z "$(gofmt -l .)"');
      if (state.automation.linting) runCmd.push("go vet ./...");
      if (state.automation.tests) runCmd.push("go test ./...");
      runCmd.push("go build ./...");
      files.push(toFile(".github/workflows/ci.yml", buildGoCiWorkflow(runCmd)));
    } else if (state.techStack.language === Language.RUST) {
      const runCmd: string[] = [];
      if (state.automation.formatting) runCmd.push("cargo fmt -- --check");
      if (state.automation.linting) runCmd.push("cargo clippy -- -D warnings");
      if (state.automation.tests) runCmd.push("cargo test");
      runCmd.push("cargo build --release");
      files.push(toFile(".github/workflows/ci.yml", buildRustCiWorkflow(runCmd)));
    } else {
      files.push(
        toFile(
          ".github/workflows/ci.yml",
          `name: CI\non:\n  push:\n  pull_request:\n${buildWorkflowConcurrency("ci")}jobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions:\n      contents: read\n    steps:\n      - uses: actions/checkout@v4\n      - run: echo "Add ${state.techStack.language} CI steps"\n`,
        ),
      );
    }
  }

  if (state.automation.release) {
    files.push(
      toFile(
        ".github/workflows/release.yml",
        buildReleaseWorkflow(state.techStack.language, nodeVersion),
      ),
    );
  }

  if (state.automation.docs) {
    files.push(toFile("docs/README.md", "# Documentation\n\nAdd docs here.\n"));
    files.push(toFile("docs/index.md", "# Docs\n\nWelcome to your docs site.\n"));
    files.push(toFile("docs/guide.md", "# Guide\n\nAdd your guide here.\n"));
    files.push(toFile("docs/architecture.md", "# Architecture\n\nDescribe the system.\n"));
    files.push(
      toFile(
        "mkdocs.yml",
        "site_name: Docs\nnav:\n  - Home: docs/index.md\n  - Guide: docs/guide.md\n  - Architecture: docs/architecture.md\n",
      ),
    );
  }

  if (state.automation.securityDocs) {
    if (
      state.techStack.language === Language.TYPESCRIPT ||
      state.techStack.language === Language.JAVASCRIPT ||
      state.techStack.language === Language.PYTHON ||
      state.techStack.language === Language.GO
    ) {
      files.push(
        toFile(".github/workflows/codeql.yml", buildCodeqlWorkflow(state.techStack.language)),
      );
    }
  }

  if (
    state.techStack.language === Language.TYPESCRIPT ||
    state.techStack.language === Language.JAVASCRIPT
  ) {
    files.push(toFile("package.json", buildPackageJson(state, nodeVersion)));
    const lockfile = buildJsLockfile(state.techStack.packageManager || "npm");
    files.push(toFile(lockfile.path, lockfile.content));
    files.push(toFile(".nvmrc", buildNvmrc(nodeVersion)));
  } else if (state.techStack.language === Language.PYTHON) {
    files.push(toFile("pyproject.toml", buildPythonProject(state)));
    if (
      state.automation.ci ||
      state.automation.tests ||
      state.automation.linting ||
      state.automation.formatting
    ) {
      files.push(toFile("requirements.txt", buildPythonRequirements(state)));
    }
    if (state.automation.linting || state.automation.formatting) {
      files.push(toFile("ruff.toml", buildRuffConfig()));
    }
  } else if (state.techStack.language === Language.GO) {
    files.push(toFile("go.mod", buildGoMod(state)));
    files.push(toFile("go.sum", ""));
  } else if (state.techStack.language === Language.RUST) {
    files.push(toFile("Cargo.toml", buildCargoToml(state)));
    files.push(toFile("Cargo.lock", ""));
  }

  files.push(...buildEntryPoints(state));

  if (state.automation.tests) {
    files.push(...buildTestFiles(state));
  }

  if (state.automation.husky) {
    files.push(toFile(".husky/pre-commit", buildHuskyPreCommit(state)));
    files.push(toFile(".husky/.gitignore", "_\n"));
  }

  if (state.automation.docker) {
    files.push(toFile("Dockerfile", buildDockerfile(state, nodeVersion)));
    files.push(toFile(".dockerignore", buildDockerignore()));
  }

  return files;
};

export const mergeScaffolds = (
  generated: GeneratedFile[],
  baseline: GeneratedFile[],
): GeneratedFile[] => {
  const merged = new Map<string, GeneratedFile>();

  baseline.forEach((file) => {
    merged.set(file.path, file);
  });

  generated.forEach((file) => {
    if (merged.has(file.path) && protectedFiles.has(file.path)) {
      return;
    }
    merged.set(file.path, file);
  });

  return Array.from(merged.values());
};
